- name: Copy hosts file
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
    mode: '0644'

- name: Copy hostname file
  ansible.builtin.template:
    src: hostname.j2
    dest: /etc/hostname
    mode: '0644'
