- name: Create LUKS container
  community.crypto.luks_device:
    device: '{{ fs_partition_root }}'
    name: rootLUKS
    passphrase: '{{ fs_luks_passphrase }}'
    cipher: aes-xts-plain64
    hash: sha512
    state: opened
